config/routes.rb
StoryBuilder::Application.routes.draw do

  resources :locations

  resources :characters do 
    resources :relations
    get 'graph', :on => :member, :defaults => { :format => 'png' }
  end

  resources :stories do
    resources :roles
  end

  root :to => 'stories#index'

end

app/models/story.rb
require 'set'
class Story < ActiveRecord::Base
  scope :all_but, lambda{|story| story ? {:conditions => ["id != ?", story.id]} : {} }
  #attr_accessor :title, :description, :mood
  has_many :roles
  has_many :characters, :through => :roles
  belongs_to :superplot, :class_name => 'Story'
  has_many :subplots, :class_name => 'Story', :foreign_key => :superplot_id
  has_attached_file :picture, 
    :styles => { :medium => "300x200>", :thumb => "100x100#" },
    :default_url => "/:class/:attachment/missing_:style.png",
    :url => "/:class/:attachment/:id/:style_:basename.:extension" 
  validate :acyclic?

  def to_s
    title
  end

  def shortness_threshold
    300
  end

  def recursive_children current=Set.new
    for child in subplots
      if current.add? child
        current += child.recursive_children current
      end
    end
    current
  end

  def acyclic?
    errors.add(:superplot, "Superplot has itself at subplot") if superplot and recursive_children.include?(superplot)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  def new_role
    @story = Story.find(params[:story_id])
    @role = @story.roles.create
    
    respond_to do |format|
      format.html
      format.json {render json: @role}
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.haml
= semantic_form_for @story do |f|
  = f.inputs do
    = f.input :title
    = f.input :description
    = f.input :mood
    = f.input :superplot, :collection => Story.all_but(@story)
    = f.input :picture, :as => :file
  = f.buttons

app/views/stories/edit.html.haml
%h1 Editing story

= render 'form'

= link_to 'Show', @story
\|
= link_to 'Back', stories_path

app/views/stories/index.html.haml
-title 'Stories'
- @stories.each do |story|
  %section.listing
    %h1= link_to story.title, story
    = image_tag(story.picture.url(:thumb))
    .text
      -if story.mood.present?
        .mood
          %b Mood:
          = story.mood
      =truncate(story.description, :length => story.shortness_threshold, :separator => ' ', :omission => '…')
    %section
      -if not story.subplots.empty?
        %h1 Subplots
        %ul
          - story.subplots.each do |subplot|
            %li= link_to subplot.title, subplot
%hr.nav
= link_to 'New Story', new_story_path

app/views/stories/new.html.haml
%h1 New story

= render 'form'

= link_to 'Back', stories_path

app/views/stories/show.html.haml
-title @story.title
%p#notice= notice

%h1= @story.title
#mood
  %strong Mood:
  = @story.mood
= image_tag(@story.picture.url(:medium), :class => :picture)

%section#description
  %h1 Description
  %div
    :markdown
      #{@story.description}
%section
  %h1 Subplots
  %ul
    -for child in @story.subplots
      %li= link_to child.title, child
%section#roles
  %h1 Roles
  -for role in @story.roles
    %section
      %h1
        = link_to role.character, [@story,role]
        &mdash;
        = role.role
      =role.description
      %nav
        = link_to 'Edit', edit_story_role_path(@story, role)
        = link_to 'Destroy', [@story, role], :confirm => 'Are you sure?', :method => :delete
  = link_to 'New Role', new_story_role_path(@story)
%hr
= link_to 'Edit', edit_story_path(@story)
\|
= link_to 'Back', stories_path