config/routes.rb
StoryBuilder::Application.routes.draw do

  resources :locations

  resources :characters do 
    resources :relations
    get 'graph', :on => :member, :defaults => { :format => 'png' }
  end

  resources :stories do
    resources :roles
  end

  root :to => 'stories#index'

end

app/models/character.rb
class Character < ActiveRecord::Base
  scope :all_but, lambda{|char| char ? {:conditions => ["id != ?", char.id]} : {} }
  has_many :roles
  has_many :stories, :through => :roles
  has_many :relations
  has_many :related_characters, :through => :relations, :source => :towards
  has_attached_file :avatar, 
    :styles => { :medium => "300x300>", :thumb => "100x100#" }, 
    :default_url => "/:class/:attachment/missing_:style.png",
    :url => "/:class/:attachment/:id/:style_:basename.:extension" 

  def to_s
    name
  end

  def shortness_threshold
    200
  end
end

app/controllers/characters_controller.rb
require 'graphviz_r'
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :ok }
    end
  end

  def graph
    character = Character.find(params[:id])
    g = GraphvizR.new character.name
    g[character.id][:label => character.name, :color => 'red']
    for rel in character.relations
      g[rel.towards.id][:label => rel.towards.name]
      (g[character.id] >> g[rel.towards.id]) [:label => rel.short]
    end
    send_data g.data(params[:format]), 
      :type => 'image/png', 
      :filename => "graph.png", 
      :disposition => 'inline'
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.haml
= semantic_form_for @character, :name => "Basic" do |f|
  = f.inputs do
    = f.input :name
    = f.input :description
    = f.input :avatar, :as => :file
  = f.buttons

app/views/characters/edit.html.haml
%h1 Editing character

= render 'form'

%h2 Relations
-for char in Character.all_but(@character)
  -rel = Relation.find_or_initialize_by_character_id_and_towards_id(@character.id,char.id)
  = semantic_form_for [@character,rel] do |f|
    %h3= char.name
    = f.inputs do 
      =f.input :character, :include_blank => false
      =f.input :towards, :include_blank => false
      =f.input :short
      =f.input :description
    = f.buttons

= link_to 'Show', @character
\|
= link_to 'Back', characters_path

app/views/characters/index.html.haml
-title 'Characters'


- @characters.each do |character|
  %section.listing
    %h1= link_to character.name, character
    =image_tag character.avatar.url(:thumb)
    :markdown
      #{truncate(character.description, :length => character.shortness_threshold, :separator => ' ', :omission => '…')}

%hr.nav
= link_to 'New Character', new_character_path

app/views/characters/new.html.haml
%h1 New character

= render 'form'

= link_to 'Back', characters_path

app/views/characters/show.html.haml
%p#notice= notice

-title @character.name
%h1= @character.name
#avatar= image_tag(@character.avatar.url(:medium), :class => :avatar)

%section#description
  %h1 Description
  :markdown
    #{@character.description}
-if not @character.roles.empty?
  %section
    %h1 Roles
    %dl
      -for s in @character.roles
        %dt= s.story.title
        %dd= s.role
-if not @character.relations.empty?
  %section
    %h1 Relations
    = image_tag(graph_character_path(@character), :alt => "Character connection graph", :id=>'graph')
    -@character.relations.each do |rel|
      %h3
        = link_to rel.towards.name, character_path(rel.towards)
        &mdash;
        = rel.short
      %p= rel.description

= link_to 'Edit', edit_character_path(@character)
\|
= link_to 'Back', characters_path