config/routes.rb
StoryBuilder::Application.routes.draw do

  resources :locations

  resources :characters do 
    resources :relations
    get 'graph', :on => :member, :defaults => { :format => 'png' }
  end

  resources :stories do
    resources :roles
  end

  root :to => 'stories#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :character
  belongs_to :story
  validates :character, :story, :presence => true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :get_story

  def get_story
    @story ||= Story.find(params[:story_id])
  end
  # GET /roles
  # GET /roles.json
  def index
    @roles = @story.roles

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = @story.roles.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to [@story, @role], notice: 'Role was successfully created.' }
        format.json { render json: [@story, @role], status: :created, location: [@story, @role] }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to [@story, @role], notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to story_roles_url(@story) }
      format.json { head :ok }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= semantic_form_for [@story, @role] do |f|
  = f.inputs
  = f.buttons

app/views/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', [@story, @role]
\|
= link_to 'Back', story_roles_path(@story)

app/views/roles/index.html.haml
-title do
  =@story.title
  &ndash; Roles

.listing
  - @roles.each do |role|
    %section
      %h1
        = link_to role.character, [@story,role]
        &mdash;
        = role.role
      = role.description
      %nav
        = link_to 'Edit', edit_story_role_path(@story, role)
        = link_to 'Destroy', [@story, role], :confirm => 'Are you sure?', :method => :delete

%hr
= link_to 'New Role', new_story_role_path(@story)

app/views/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', story_roles_path(@story)

app/views/roles/show.html.haml
%p#notice= notice

%p
  %b Character:
  = @role.character
%p
  %b Story:
  = @role.story
%p
  %b Role:
  = @role.role
%p
  %b Description:
  = @role.description

= link_to 'Edit', edit_story_role_path(@story, @role)
\|
= link_to 'Back', story_roles_path(@story)