config/routes.rb
StoryBuilder::Application.routes.draw do

  resources :locations

  resources :characters do 
    resources :relations
    get 'graph', :on => :member, :defaults => { :format => 'png' }
  end

  resources :stories do
    resources :roles
  end

  root :to => 'stories#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= semantic_form_for @location do |f|
  = f.inputs
  = f.buttons

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
-title 'Locations'

%table
  %tr
    %th Name
    %th Description
    %th Image
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.name
      %td= location.description
      %td= location.image
      %td= link_to 'Show', location
      %td= link_to 'Edit', edit_location_path(location)
      %td= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name
%p
  %b Description:
  = @location.description
%p
  %b Image:
  = @location.image

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path